version: '3.1'

services:
  service:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    image: backend-node-service:local
    container_name: backend-node-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVICE_PORT=4200
    env_file:
      - .env
    volumes:
      - backend-node-service:/home/src/app
    networks:
      - backend-network
    ports:
      - 4200:4200

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend-network
    ports:
      - 5672:5672
      - 15672:15672 # GUI

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  backend-node-service:
    name: backend-node-service
    driver: local
  rabbitmq-data:
    name: rabbitmq-data
    driver: local
