export const EVENT_SDK_OPTIONS = 'EVENT_SDK_OPTIONS';
export const EVENT_SDK_CONSUMER_METADATA = 'EVENT_SDK_CONSUMER_METADATA';

export const EVENT_SDK_PRODUCER_TOKEN = 'EVENT_SDK_PRODUCER_TOKEN';
export const EVENT_SDK_CONSUMER_TOKEN = 'EVENT_SDK_CONSUMER_TOKEN';
