service:
  name: SERVICE_NAME
  description: SERVICE_DESCRIPTION
  host: SERVICE_HOST
  port:
    __name: SERVICE_PORT
    __format: json
  protocol: SERVICE_PROTOCOL
  baseUrl: SERVICE_BASE_URL
  docsUrl: SERVICE_DOCS_URL

logger:
  type: LOGGER_TYPE
  level: LOGGER_LOG_LEVEL
  enabled:
    __name: LOGGER_LOG_ENABLED
    __format: json
  colorEnabled:
    __name: LOGGER_COLOR_ENABLED
    __format: json
  prettyEnabled:
    __name: LOGGER_PRETTY_ENABLED
    __format: json
  redact:
    enabled:
      __name: LOGGER_REDACT_ENABLED
      __format: json
    censor: LOGGER_REDACT_CENSOR
    paths:
      __name: LOGGER_REDACT_PATHS
      __format: json

paymentGateway:
  stripe:
    publicKey: STRIPE_PUBLIC_KEY
    secretKey: STRIPE_SECRET_KEY
    testMode:
      __name: STRIPE_TEST_MODE
      __format: json

rabbitmq:
  uri: RABBITMQ_URI

kafka:
  broker: KAFKA_BROKER

database:
  auth:
    host: DATABASE_AUTH_HOST
    port:
      __name: DATABASE_AUTH_PORT
      __format: json
    user: DATABASE_AUTH_USER
    password: DATABASE_AUTH_PASSWORD
    database: DATABASE_AUTH_DATABASE
    schema: DATABASE_AUTH_SCHEMA
    connectionTimeout:
      __name: DATABASE_AUTH_CONNECTION_TIMEOUT
      __format: json
    maxQueryExecutionTime:
      __name: DATABASE_AUTH_MAX_QUERY_EXECUTION_TIME
      __format: json
    poolSize:
      __name: DATABASE_AUTH_POOL_SIZE
      __format: json
  account:
    host: DATABASE_ACCOUNT_HOST
    port:
      __name: DATABASE_ACCOUNT_PORT
      __format: json
    user: DATABASE_ACCOUNT_USER
    password: DATABASE_ACCOUNT_PASSWORD
    database: DATABASE_ACCOUNT_DATABASE
    schema: DATABASE_ACCOUNT_SCHEMA
    connectionTimeout:
      __name: DATABASE_ACCOUNT_CONNECTION_TIMEOUT
      __format: json
    maxQueryExecutionTime:
      __name: DATABASE_ACCOUNT_MAX_QUERY_EXECUTION_TIME
      __format: json
    poolSize:
      __name: DATABASE_ACCOUNT_POOL_SIZE
      __format: json
