service:
  name: SERVICE_NAME
  description: SERVICE_DESCRIPTION
  host: SERVICE_HOST
  port:
    __name: SERVICE_PORT
    __format: json
  protocol: SERVICE_PROTOCOL
  baseUrl: SERVICE_BASE_URL
  docsUrl: SERVICE_DOCS_URL
