service:
  name: SERVICE_NAME
  description: SERVICE_DESCRIPTION
  host: SERVICE_HOST
  port:
    __name: SERVICE_PORT
    __format: json
  protocol: SERVICE_PROTOCOL
  baseUrl: SERVICE_BASE_URL
  docsUrl: SERVICE_DOCS_URL

logger:
  type: LOGGER_TYPE
  level: LOGGER_LOG_LEVEL
  enabled:
    __name: LOGGER_LOG_ENABLED
    __format: json
  colorEnabled:
    __name: LOGGER_COLOR_ENABLED
    __format: json
  prettyEnabled:
    __name: LOGGER_PRETTY_ENABLED
    __format: json
  redact:
    enabled:
      __name: LOGGER_REDACT_ENABLED
      __format: json
    censor: LOGGER_REDACT_CENSOR
    paths:
      __name: LOGGER_REDACT_PATHS
      __format: json
