service:
  name:
  description:
  host: 127.0.0.1
  port: 4000
  protocol: http
  baseUrl: /api
  docsUrl: /docs

pino:
  level: debug
  enabled: true
  colorEnabled: true
  prettyEnabled: true
  redact:
    enabled: true
    censor: '******'
    paths:
      - '*.headers["access-token"]'
