service:
  name:
  description:
  host: 127.0.0.1
  port: 4000
  protocol: http
  baseUrl: /
  docsUrl: /docs

logger:
  type: pino
  level: debug
  enabled: true
  colorEnabled: true
  prettyEnabled: true
  redact:
    enabled: true
    censor: '******'
    paths:
      - 'headers["access-token"]'
      - 'headers.cookie'
      - password
      - secret

paymentGateway:
  stripe:
    publicKey:
    secretKey:
    testMode: true

rabbitmq:
  uri: amqp://127.0.0.1:5672
  isCustomClient: false

kafka:
  broker: 127.0.0.1:9092
  isCustomClient: false

postgres:
  auth:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    database: auth
    schema: public
    connectionTimeout: 10000
    maxQueryExecutionTime: 30000
    poolSize: 1
    migrationsRun: true
  account:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    database: account
    schema: public
    connectionTimeout: 10000
    maxQueryExecutionTime: 30000
    poolSize: 1
    migrationsRun: true

mongodb:
  auth:
    host: 127.0.0.1
    port: 27017
    user:
    password:
    database: auth
    directConnection: false

dataModel:
  userSession:
    deleteAt: 31536000 # 365 days

jwt:
  secret:
  expiresIn: 1h
