service:
  name:
  description:
  host: 127.0.0.1
  port: 4000
  protocol: http
  baseUrl: /
  docsUrl: /docs

logger:
  type: pino
  level: debug
  enabled: true
  colorEnabled: true
  prettyEnabled: true
  redact:
    enabled: true
    censor: '******'
    paths:
      - '*.headers["access-token"]'
      - password
      - secret

paymentGateway:
  stripe:
    publicKey:
    secretKey:
    testMode: true

rabbitmq:
  uri: amqp://127.0.0.1:5672

kafka:
  broker: 127.0.0.1:9092

database:
  auth:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    database: auth
    schema: public
    connectionTimeout: 10000
    maxQueryExecutionTime: 30000
    poolSize: 1
  account:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    database: account
    schema: public
    connectionTimeout: 10000
    maxQueryExecutionTime: 30000
    poolSize: 1
