logger:
  enabled: false
  prettyEnabled: false

rabbitmq:
  isCustomClient: false

kafka:
  isCustomClient: false
  allowAutoTopicCreation: false

postgres:
  auth:
    migrationsRun: false
  account:
    migrationsRun: false
