name: Build Docker Image

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'
      imageName:
        type: string
        required: false
        default: 'backend-node-service'
      tag:
        type: string
        required: false
        default: 'latest'

jobs:
  build-docker-image:
    runs-on: ['${{ inputs.runner }}']
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ inputs.imageName }}:${{ inputs.tag }}
          outputs: type=docker,dest=/tmp/${{ inputs.imageName }}-${{ inputs.tag }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.imageName }}-${{ inputs.tag }}
          path: /tmp/${{ inputs.imageName }}-${{ inputs.tag }}.tar
          retention-days: 1
