name: CD

on:
  push:
    branches:
      - 'master'

jobs:
  cd:
    name: Continue Deployment
    uses: ./.github/workflows/jobs/release-tag.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
