name: Continue Deployment

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  cd:
    name: Continue Deployment
    uses: ./.github/workflows/release-tag.yml
    secrets: inherit
