name: Continue Integration

on:
  pull_request:
    branches:
      - master

jobs:
  check-version:
    name: Check Version
    uses: ./.github/workflows/check-version.yml
    secrets: inherit

  unit-test:
    name: Unit Test
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
