name: Continue Integration

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  check-version:
    name: Check Version
    uses: ./.github/actions/check-version.yml
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}

  prepare:
    name: Prepare
    uses: ./.github/actions/prepare.yml
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}

  lint:
    name: Lint
    uses: ./.github/actions/lint.yml
    secrets: inherit
    needs: [prepare]
    with:
      runner: ${{ inputs.runner }}

  dependencies-scan:
    name: Dependencies Scan
    uses: ./.github/actions/dependencies-scan.yml
    secrets: inherit
    needs: [prepare]
    with:
      runner: ${{ inputs.runner }}

  unit-test:
    name: Unit Test
    uses: ./.github/actions/unit-test.yml
    secrets: inherit
    needs: [prepare]
    with:
      runner: ${{ inputs.runner }}

  e2e-test:
    name: E2E Test
    uses: ./.github/actions/e2e-test.yml
    secrets: inherit
    needs: [prepare]
    with:
      runner: ${{ inputs.runner }}

  bvt-test:
    name: BVT Test
    uses: ./.github/actions/bvt-test.yml
    secrets: inherit
    needs: [prepare]
    with:
      runner: ${{ inputs.runner }}

  build-docker-image:
    name: Build Docker Image
    uses: ./.github/actions/build-docker-image.yml
    needs: [unit-test, e2e-test]
    with:
      runner: ${{ inputs.runner }}

  docker-image-scan:
    name: Docker Image Scan
    uses: ./.github/actions/docker-image-scan.yml
    needs: [build-docker-image]
    with:
      runner: ${{ inputs.runner }}
