name: Continue Integration

on:
  pull_request:
    branches:
      - master

jobs:
  check-version:
    name: Check Version
    uses: ./.github/workflows/check-version.yml
    secrets: inherit

  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml
    secrets: inherit

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit
    needs: [prepare]

  unit-test:
    name: Unit Test
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
    needs: [prepare]

  e2e-test:
    name: E2E Test
    uses: ./.github/workflows/e2e-test.yml
    secrets: inherit
    needs: [prepare]

  bvt-test:
    name: BVT Test
    uses: ./.github/workflows/bvt-test.yml
    secrets: inherit
    needs: [prepare]
