on:
  workflow_call:
    inputs:
      RUNNER:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  dependencies-scan:
    name: Dependencies Scan
    runs-on: ['${{ inputs.RUNNER }}']
    timeout-minutes: 10

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Restore cached node_modules
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install dependencies if cache missed
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Generate audit reports
        id: npm-audit
        if: ${{ always() }}
        run: |
          status=0
          npm i -g audit-export @netly/npm-audit-markdown
          npm audit --json | audit-export --title "NPM Audit Report"
          npm audit --json | npx @netly/npm-audit-markdown --output audit-report.md
          npm audit --json --audit-level=high || status=$?
          exit $status

      - name: Archive audit html report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: report-vulnerability-dependencies
          path: ./audit-report.html
          retention-days: 1
          include-hidden-files: false

      - name: Attach audit report to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ always() && github.event_name == 'pull_request' }}
        with:
          header: dependencies-scan-report
          path: audit-report.md

      - name: Attach audit check status
        uses: LouisBrunner/checks-action@v2
        if: ${{ always() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Dependencies Scan report
          conclusion: ${{ steps.npm-audit.outcome }}
          output: |
            {"summary": "Dependencies Scan report detail"}
          output_text_description_file: audit-report.md
