name: Prepare

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  prepare:
    runs-on: ['${{ inputs.RUNNER }}']
    timeout-minutes: 5

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

    #   - name: Cache dependencies
    #     id: cache-dependencies
    #     uses: actions/cache@v4
    #     with:
    #       path: ~/.npm
    #       key: npm-${{ hashFiles('package-lock.json') }}
    #       restore-keys: npm-
