name: Prepare

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  prepare:
    runs-on: ['${{ inputs.runner }}']
    timeout-minutes: 5

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Cache npm
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies if cache missed
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci
