name: Prepare

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  prepare:
    runs-on: ['${{ inputs.RUNNER }}']
    timeout-minutes: 5

    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules/
          retention-days: 1
