name: Publish Reports

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner'
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  publish-github-page:
    name: Publish Artifacts to Github Page
    uses: ./.github/actions/job-publish-github-page.yml
    secrets: inherit
    with:
      runner: ${{ inputs.runner }}
