name: Push Workflows

on:
  push:
    branches:
      - master
      - release/**

jobs:
  ci:
    name: Continue Integration
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      skip_if_fail: false

  cd:
    name: Continue Deployment
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    needs: [ci]
