name: Release Tag

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        description: 'The tag to be created'
      package-json-path:
        required: false
        type: string
        default: 'package.json'

jobs:
  release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Get version from package.json
        id: get_version
        run: |
          PACKAGE_JSON_PATH="${{ inputs['package-json-path'] }}"
          VERSION=$(jq -r '.version' $PACKAGE_JSON_PATH)
          echo "Version from package.json: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Create the tag
        id: create_tag
        run: |
          TAG="${{ inputs.tag || steps.get_version.outputs.version }}"
          echo "Creating tag: $TAG"
          git tag $TAG
          git push origin $TAG

      - name: Confirm the created tag
        run: |
          git fetch --tags
          echo "The created tag is: $(git describe --tags)"
